# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# default prompt with some changes on the linebreak position:
format = """
$username\
$hostname\
$localip\
$directory\
$shlvl\
$singularity\
$kubernetes\
$sudo\
$jobs\
$battery\
$time\
$cmd_duration\
$vcsh\
$fossil_branch\
$fossil_metrics\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$hg_branch\
$pijul_channel\
$docker_context\
$package\
$c\
$cmake\
$cobol\
$daml\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$fennel\
$gleam\
$golang\
$guix_shell\
$haskell\
$haxe\
$helm\
$java\
$julia\
$kotlin\
$gradle\
$lua\
$nim\
$nodejs\
$ocaml\
$opa\
$perl\
$php\
$pulumi\
$purescript\
$python\
$quarto\
$raku\
$rlang\
$red\
$ruby\
$rust\
$scala\
$solidity\
$swift\
$terraform\
$typst\
$vlang\
$vagrant\
$zig\
$buf\
$nix_shell\
$conda\
$meson\
$spack\
$memory_usage\
$aws\
$gcloud\
$openstack\
$azure\
$nats\
$direnv\
$env_var\
$crystal\
$custom\
$status\
$os\
$container\
$shell\
$line_break\
$character\
"""

# Inserts a blank line between shell prompts
add_newline = true

[character]
# my preferred characters
success_symbol = "[\\$](bold green)"
error_symbol = "[x](bold red)"
vimcmd_symbol = "[%](bold green)"

[username]
show_always = true
style_user = 'red bold'
style_root = 'black bold'
format = '[$user]($style)'
disabled = false
# aliases = { "kusno" = "me" }

[hostname]
disabled = false
ssh_only = false
format = '@[$ssh_symbol$hostname](bold red)'
# trim_at = '.mudiarto.com'

[directory]
format = ':[$path]($style)[$read_only]($read_only_style) '
# read_only = " ro"


[time]
# from: https://starship.rs/config/#time
disabled = false
format = '[\[ $time \]]($style) '
time_format = '%Y/%m/%dT%H:%M:%SZ'
utc_time_offset = '0'
# time_range = '10:00:00-14:00:00'

[cmd_duration]
min_time = 2_000
