name: ci

on:
  push:
  pull_request:

jobs:
  # to be able to use chezmoi on github codespace directly
  clone-and-install:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/vscode/devcontainers/base:ubuntu
      env:
        CODESPACES: true
    steps:
      - uses: actions/checkout@v2
      - run: ./install.sh
      - name: chezmoi data
        run: '"$HOME/.local/bin/chezmoi" data'
